new changes made 02

diff --git a/jktest.gocd.yaml b/jktest.gocd.yaml
--- a/jktest.gocd.yaml
+++ b/jktest.gocd.yaml
@@ -36,7 +36,7 @@ pipelines:
                           sudo mv /home/joshi/prime-square/core-*.jar /home/joshi/archive/core-$(date +%F-%T).jar || { echo "Failed to archive core JAR"; exit 1; }
 
                           echo "Replacing core JAR..."
-                          sudo mv /home/joshi/archive/temp-extract/core-*.jar /home/joshi/prime-square/ || { echo "Failed to replace core JAR"; exit 1; }
+                          sudo mv /home/joshi/archive/temp-extract/core-*.jar /home/joshi/prime-square/ || { echo "Failed to replace core JAR"; exit 0; }
 
                           echo "Preparing for Database Update..."
                           echo "REGULAR_DEPLOYMENT" > /home/joshi/deployment_type
