new changes made 05

diff --git a/jktest.gocd.yaml b/jktest.gocd.yaml
--- a/jktest.gocd.yaml
+++ b/jktest.gocd.yaml
@@ -119,67 +119,144 @@ pipelines:
                         fi
 
 
-      - Regular-deployment:
-          fetch_materials: false
+      - Deploy-Backend:
+          fetch_materials: true
+          keep_artifacts: false
           clean_workspace: false
+          approval:
+            type: manual
           jobs:
-            Regular-deployment:
+            run-commands:
+              timeout: 0
+              variables:
+                BUILD_DIR: /home/joshi/builds
+                BE_TARGET_DIR: /home/joshi/prime
+                BE_ARCHIVE_DIR: /home/joshi/archive
+                SERVICE: PrimeSquare.service
+                DB_SCRIPTS_DIR: /home/joshi/prime-square/database-scripts
+                DB_USER: psdbadmin
+                DB_PASS: 6%EOm@Te1sb19Th6
+                SFTP_HOST: 172.16.7.116
+                SFTP_USER: surya
+                SFTP_UPLOADS_DIR: uploads
               tasks:
                 - exec:
                     command: /bin/bash
                     arguments:
                       - -c
                       - |
+                        echo "Exporting environment variables..."
                         export BUILD_DIR=/home/joshi/builds
-
                         export BE_TARGET_DIR=/home/joshi/prime-square
-
+                        export UI_TARGET_DIR=/var/www/html
                         export BE_ARCHIVE_DIR=/home/joshi/archive
-
+                        export UI_ARCHIVE_DIR=/home/joshi/ui-archive
+                        export BE_TEMP_DIR=${BE_ARCHIVE_DIR}/temp-extract
+                        export UI_TEMP_DIR=${UI_ARCHIVE_DIR}/temp-extract
+                        export SERVICE=PrimeSquare.service
+                        export DB_SCRIPTS_DIR=/home/joshi/prime-square/database-scripts
+                        export DB_USER=psdbadmin
+                        export DB_PASS=6%EOm@Te1sb19Th6
                         export SFTP_HOST=172.16.7.116
-
                         export SFTP_USER=surya
-
                         export SFTP_KEY=/var/go/.ssh/id_rsa
-
                         export SFTP_UPLOADS_DIR=uploads
 
-
-
-                        DEPLOYMENT_TYPE=$(cat deployment_type.txt)
-
-                        if [ "$DEPLOYMENT_TYPE" == "REGULAR_DEPLOYMENT" ]; then
-                          
-                          echo "Accessing SFTP machine to fetch the backend zip file..."
-
-                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
-
-                        cd ${SFTP_UPLOADS_DIR}
-
-                        get ps_be_*.zip ${BUILD_DIR}
-
-                        bye
-
-                        EOF
-
-
-                          if [ $? -ne 0 ]; then
-                            echo "Failed to fetch backend.zip from SFTP."
-                            exit 1
+                        echo "Checking if service ${SERVICE} exists..."
+                        if [ -f /etc/systemd/system/${SERVICE} ]; then
+                          echo "${SERVICE} exists. Checking service status..."
+                          sudo systemctl status ${SERVICE} > /dev/null 2>&1
+                          if [ $? -eq 0 ]; then
+                            echo "${SERVICE} is running. Stopping the service..."
+                            sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
+                          else
+                            echo "${SERVICE} is not running."
                           fi
-                          
-                          echo "Unzipping the backend artifacts to BE_TARGET_DIR..."
-                          sudo unzip -o "${BUILD_DIR}/ps_be_*.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }
-
-                          echo "Replacing core JAR..."
-                          sudo mv /home/joshi/archive/core-*.jar /home/joshi/prime-square/ || { echo "Failed to replace core JAR"; exit 0; }
-
-                          echo "Changing permissions of BE_TARGET_DIR to joshi:joshi..."
-                          sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
                         else
-                          echo "Skipping regular deployment."
-                          exit 0
+                          echo "${SERVICE} does not exist. Proceeding..."
                         fi
+ 
+                        echo "Checking and creating BUILD_DIR if needed..."
+                        if [ ! -d "${BUILD_DIR}" ]; then
+                          echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
+                          mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
+                        else
+                          echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
+                        fi
+ 
+                        echo "Checking for existing backend files in BUILD_DIR..."
+                         if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
+                          echo "Found existing ps_be_*.zip files. Removing them..."
+                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
+                        else
+                        echo "No existing ps_be_*.zip files found. Proceeding..."
+                        fi
+ 
+                        echo "Accessing SFTP machine to fetch the backend zip file..."
+                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
+                        cd ${SFTP_UPLOADS_DIR}
+                        get ps_be_*.zip ${BUILD_DIR}
+                        bye
+                        EOF
+                        
+                        if [ $? -ne 0 ]; then
+                          echo "Failed to fetch backend.zip from SFTP."
+                          exit 1
+                        fi
+ 
+                        echo "Checking and creating BE_TARGET_DIR if needed..."
+                        if [ ! -d "${BE_TARGET_DIR}" ]; then
+                          echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
+                          sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
+                        else
+                          echo "BE_TARGET_DIR exists. Using existing ${BE_TARGET_DIR}..."
+                        fi
+ 
+                        echo "Changing permissions of BE_TARGET_DIR to joshi:joshi..."
+                        sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
+ 
+                        echo "Unzipping the backend artifacts to BE_TARGET_DIR..."
+                        sudo unzip -o "${BUILD_DIR}/ps_be_*.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }
+ 
+                        echo "Listing extracted files in BE_TARGET_DIR..."
+                        ls -l "${BE_TARGET_DIR}"
+ 
+                        echo "Changing permissions of BE_TARGET_DIR and BUILD_DIR to joshi:joshi..."
+                        sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }                
+ 
+                        echo "Checking and copying service file if needed..."
+                        if [ ! -f /etc/systemd/system/${SERVICE} ]; then
+                          sudo cp "${BE_TARGET_DIR}/service/${SERVICE}" /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }
+ 
+                        echo "Enabling the service..."
+                          sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
+ 
+                        else
+                          echo "Service file already exists. Skipping copy."
+                        fi
+ 
+                        echo "Making wrapper.sh executable..."
+                        sudo chmod +x "${BE_TARGET_DIR}/wrapper.sh" || { echo "Failed to make wrapper.sh executable"; exit 1; }
+ 
+                        echo "Reloading systemd daemon..."
+                        sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
+ 
+                        echo "Giving execute permissions to database scripts..."
+                        sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }
+ 
+                        echo "Executing database scripts..."
+                        mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute ps_index_create.sql"; exit 1; }
+
+                        sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
+                        echo "starting service..."
+                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
+                        sudo systemctl status ${SERVICE}
+ 
+                        echo "Deployment complete."
 
 
       - Database-Update:
