sftp_changes 08

diff --git a/jktest.gocd.yaml b/jktest.gocd.yaml
--- a/jktest.gocd.yaml
+++ b/jktest.gocd.yaml
@@ -136,7 +136,7 @@ pipelines:
               timeout: 0
               variables:
                 BUILD_DIR: /home/joshi/builds
-                BE_TARGET_DIR: /home/joshi/prime
+                BE_TARGET_DIR: /home/joshi/prime-square
                 BE_ARCHIVE_DIR: /home/joshi/archive
                 SERVICE: PrimeSquare.service
                 DB_SCRIPTS_DIR: /home/joshi/prime-square/database-scripts
@@ -170,6 +170,23 @@ pipelines:
                         if [ "$DEPLOYMENT_TYPE" == "REGULAR_DEPLOYMENT" ]; then
                           echo "Regular deployment detected. Setting up environment..."
 
+                        echo "Accessing SFTP machine to fetch the backend zip file..."
+
+                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
+                        
+                        cd ${SFTP_UPLOADS_DIR}
+                        
+                        get ps_be_*.zip ${BUILD_DIR}
+                        
+                        bye
+                        
+                        EOF
+
+                          if [ $? -ne 0 ]; then
+                            echo "Failed to fetch backend.zip from SFTP."
+                            exit 1
+                          fi  
+
                           echo "Checking if service ${SERVICE} exists..."
                           if [ -f /etc/systemd/system/${SERVICE} ]; then
                             echo "${SERVICE} exists. Checking service status..."
@@ -200,11 +217,16 @@ pipelines:
                           echo "No existing ps_be_*.zip files found. Proceeding..."
                           fi
   
-                          echo "Accessing SFTP machine to fetch the backend zip file..."
+                        echo "Accessing SFTP machine to fetch the backend zip file..."
+
                         sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
+                        
                         cd ${SFTP_UPLOADS_DIR}
+                        
                         get ps_be_*.zip ${BUILD_DIR}
+                        
                         bye
+                        
                         EOF
 
                           if [ $? -ne 0 ]; then
