sftp_changes 06

diff --git a/jktest.gocd.yaml b/jktest.gocd.yaml
--- a/jktest.gocd.yaml
+++ b/jktest.gocd.yaml
@@ -136,8 +136,6 @@ pipelines:
           fetch_materials: true
           keep_artifacts: false
           clean_workspace: false
-          approval:
-            type: manual
           jobs:
             run-commands:
               timeout: 0
@@ -177,101 +175,92 @@ pipelines:
                         if [ "$DEPLOYMENT_TYPE" == "REGULAR_DEPLOYMENT" ]; then
                           echo "Regular deployment detected. Setting up environment..."
 
-                        echo "Checking if service ${SERVICE} exists..."
-                        if [ -f /etc/systemd/system/${SERVICE} ]; then
-                          echo "${SERVICE} exists. Checking service status..."
-                          sudo systemctl status ${SERVICE} > /dev/null 2>&1
-                          if [ $? -eq 0 ]; then
-                            echo "${SERVICE} is running. Stopping the service..."
-                            sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
+                          echo "Checking if service ${SERVICE} exists..."
+                          if [ -f /etc/systemd/system/${SERVICE} ]; then
+                            echo "${SERVICE} exists. Checking service status..."
+                            sudo systemctl status ${SERVICE} > /dev/null 2>&1
+                            if [ $? -eq 0 ]; then
+                              echo "${SERVICE} is running. Stopping the service..."
+                              sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
+                            else
+                              echo "${SERVICE} is not running."
+                            fi
                           else
-                            echo "${SERVICE} is not running."
+                            echo "${SERVICE} does not exist. Proceeding..."
                           fi
-                        else
-                          echo "${SERVICE} does not exist. Proceeding..."
-                        fi
- 
-                        echo "Checking and creating BUILD_DIR if needed..."
-                        if [ ! -d "${BUILD_DIR}" ]; then
-                          echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
-                          mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
-                        else
-                          echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
-                        fi
- 
-                        echo "Checking for existing backend files in BUILD_DIR..."
-                         if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
-                          echo "Found existing ps_be_*.zip files. Removing them..."
-                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
-                        else
-                        echo "No existing ps_be_*.zip files found. Proceeding..."
-                        fi
- 
-                        echo "Accessing SFTP machine to fetch the backend zip file..."
-                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
-                        cd ${SFTP_UPLOADS_DIR}
-                        get ps_be_*.zip ${BUILD_DIR}
-                        bye
-                        EOF
+  
+                          echo "Checking and creating BUILD_DIR if needed..."
+                          if [ ! -d "${BUILD_DIR}" ]; then
+                            echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
+                            mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
+                          else
+                            echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
+                          fi
+  
+                          echo "Checking for existing backend files in BUILD_DIR..."
+                          if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
+                            echo "Found existing ps_be_*.zip files. Removing them..."
+                            sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
+                          else
+                          echo "No existing ps_be_*.zip files found. Proceeding..."
+                          fi
+  
+                          echo "Accessing SFTP machine to fetch the backend zip file..."
+                          sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
+                          cd ${SFTP_UPLOADS_DIR}
+                          get ps_be_*.zip ${BUILD_DIR}
+                          bye
+                          EOF
 
-                        if [ $? -ne 0 ]; then
-                          echo "Failed to fetch backend.zip from SFTP."
-                          exit 1
-                        fi
- 
-                        echo "Checking and creating BE_TARGET_DIR if needed..."
-                        if [ ! -d "${BE_TARGET_DIR}" ]; then
-                          echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
-                          sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
-                        else
-                          echo "BE_TARGET_DIR exists. Using existing ${BE_TARGET_DIR}..."
-                        fi
- 
-                        echo "Changing permissions of BE_TARGET_DIR to joshi:joshi..."
-                        sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
- 
-                        echo "Unzipping the backend artifacts to BE_TARGET_DIR..."
-                        sudo unzip -o "${BUILD_DIR}/ps_be_*.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }
- 
-                        echo "Listing extracted files in BE_TARGET_DIR..."
-                        ls -l "${BE_TARGET_DIR}"
- 
-                        echo "Changing permissions of BE_TARGET_DIR and BUILD_DIR to joshi:joshi..."
-                        sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }                
- 
-                        echo "Checking and copying service file if needed..."
-                        if [ ! -f /etc/systemd/system/${SERVICE} ]; then
-                          sudo cp "${BE_TARGET_DIR}/service/${SERVICE}" /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }
- 
-                        echo "Enabling the service..."
-                          sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
- 
-                        else
-                          echo "Service file already exists. Skipping copy."
-                        fi
- 
-                        echo "Making wrapper.sh executable..."
-                        sudo chmod +x "${BE_TARGET_DIR}/wrapper.sh" || { echo "Failed to make wrapper.sh executable"; exit 1; }
- 
-                        echo "Reloading systemd daemon..."
-                        sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
- 
-                        echo "Giving execute permissions to database scripts..."
-                        sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }
- 
-                        echo "Executing database scripts..."
-                        mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
-                        mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
-                        mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
-                        mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
-                        mysql < "${DB_SCRIPTS_DIR}/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} -h 172.16.7.115 || { echo "Failed to execute ps_index_create.sql"; exit 1; }
+                          if [ $? -ne 0 ]; then
+                            echo "Failed to fetch backend.zip from SFTP."
+                            exit 1
+                          fi
+  
+                          echo "Checking and creating BE_TARGET_DIR if needed..."
+                          if [ ! -d "${BE_TARGET_DIR}" ]; then
+                            echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
+                            sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
+                          else
+                            echo "BE_TARGET_DIR exists. Using existing ${BE_TARGET_DIR}..."
+                          fi
+  
+                          echo "Changing permissions of BE_TARGET_DIR to joshi:joshi..."
+                          sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
+  
+                          echo "Archiving existing core JAR..."
+                          sudo mv /home/joshi/prime-square/core-*.jar /home/joshi/archive/core-$(date +%F-%T).jar || { echo "Failed to archive core JAR"; exit 1; }
 
-                        sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
-                        echo "starting service..."
-                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
-                        sudo systemctl status ${SERVICE}
- 
-                        echo "Deployment complete."
+                            
+                          echo "Replacing core JAR..."
+                          sudo mv /home/joshi/archive/core-*.jar /home/joshi/prime-square/ || { echo "Failed to replace core JAR"; exit 1; }
+                        
+  
+                          echo "Listing extracted files in BE_TARGET_DIR..."
+                          ls -l "${BE_TARGET_DIR}"
+  
+                          echo "Changing permissions of BE_TARGET_DIR and BUILD_DIR to joshi:joshi..."
+                          sudo chown -R joshi:joshi "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }                
+  
+                          echo "Checking and copying service file if needed..."
+                          if [ ! -f /etc/systemd/system/${SERVICE} ]; then
+                            sudo cp "${BE_TARGET_DIR}/service/${SERVICE}" /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }
+  
+                          echo "Enabling the service..."
+                            sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
+  
+                          else
+                            echo "Service file already exists. Skipping copy."
+                          fi
+  
+                          echo "Making wrapper.sh executable..."
+                          sudo chmod +x "${BE_TARGET_DIR}/wrapper.sh" || { echo "Failed to make wrapper.sh executable"; exit 1; }
+  
+                          echo "Reloading systemd daemon..."
+                          sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
+  
+                          echo "Deployment complete."
+                          echo "Approve the Database-Update stage for recreation of DB" 
 
 
       - Database-Update:
@@ -302,7 +291,10 @@ pipelines:
                           echo "Manual approval granted. Executing database update..."
                           echo "SKIP_DB_UPDATE=false" > /home/joshi/pipeline_flags
                         fi  
-
+                        
+                        echo "Giving execute permissions to database scripts..."
+                        sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }
+                        
                         if [ "$DEPLOYMENT_TYPE" == "REGULAR_DEPLOYMENT" ]; then
                           echo "Executing database scripts for regular deployment..."
                           mysql < /home/joshi/prime-square/database-scripts/ddl_drop_schema_script.sql -u psdbadmin -p6%EOm@Te1sb19Th6 -h 172.16.7.115 || { echo "Failed to drop schema"; exit 1; }
